### ISSUE TITLE
How does Aeryn scale?

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Aeryn#13]
![](http://gifs.ashfurrow.com/scale.gif)

Right now, we have a 1:1 relationship between Heroku dynos (our recommended deploy option) and GitHub repos to invite users to. This works well for _just_ Moya, but doesn't scale well when you have several repos with the same exact needs.

Not sure what this could/should look like yet. The GitHub API has support for creating WebHooks on repos, so that's something we could automate with Aeryn. Probably best to keep a 1:1 dyno-to-org ratio so we can avoid duplicate welcome messages (and few people will be using Aeryn for more than one organization I think).

I'm looking for feedback on what users would expect, how this might be implemented (comma-separated list of repositories?), and Aeryn's role in the whole thing. So far, I'm the biggest user, so I'll reflect on this too. 

EDIT: I guess we kind of already support this, -ish, since Moya/Moya and Moya/Aeryn are running the same dyno. It's just the work to duplicate WebHook configurationss across repos that's challenging.

**Comment by orta** [comment]
Hrm, so you ideally would deploy one Aeryn per org right? Cause you can have multiple repos inside the org pointing to the same app ( as it would give access per org ) giving access to the same team

**Comment by ashfurrow** [comment]
Yeah exactly (sorry, edited issue to reflect this). I guess we really just need a way to make WebHook configuration easier? Or maybe it's not a problem that needs solving.

**Comment by ashfurrow** [comment]
I just set up Aeryn across ten or so RxSwiftCommunity repos, just copy/pasting the payload URL and WebHook secret. Took about five minutes total, maybe this is just something worth documenting, to let people know there's no better way? We could also provide a script to automate this process from the command line.

**Comment by orta** [comment]
IMO, _probably_ worth doing, might take longer to go get an access token and set all that jazz up, but that's probably the amount of time to do 3-5 repos.

**Comment by orta** [comment]
I'd like to propose that this would make a really simple Peril "plugin" - plugins don't exist in Peril, but I think it could be implemented pretty simply in Peril and then abstracted into a plugin.

**Comment by ashfurrow** [comment]
Makes sense to me – the key would be the proper access rights / token scope, and documenting it.

**Comment by SD10** [comment]
@ashfurrow I notice you use your personal account to invite new users to the GitHub organization. I was concerned about having this automation on my personal account (didn't know if it breached GitHub's ToS) but you seem to have been doing it for awhile without issues. Any reason why this is not being done by a bot? To restrict access rights?

Basically, this is something I want to set up for [MessageKit](https://github.com/MessageKit/MessageKit) once I get the project stable. Ideally, I'd like to run that project the same way as Moya.

**Comment by orta** [comment]
@SD10 it can use you `DANGER_GITHUB_ACCESS_TOKEN` - then it's definitely not breaking the TOS - assuming you're agin danger

**Comment by SD10** [comment]
@orta Good point! 

I'd like to use the same bot running Danger to invite users to the organization, but that would require me to invite the bot to the org I believe. The danger getting started guide tells me not to do this. I guess that would give the bot too much power over the organization?

**Comment by orta** [comment]
Ah yeah, that's correct - you'd have to make another bot account that does have access. More faffing.

**Comment by ashfurrow** [comment]
Yup yup – I didn't want to bother setting up (another) bot account, so I used my own. Plus it gives it a personal touch 😉

**Comment by SD10** [comment]
Thank you, both~ I appreciate the guidance ❤️

**Comment by orta** [comment]
Here's a Peril version: https://github.com/danger/peril-settings/blob/master/org/closed-prs.ts#L18-L58

**Comment by ashfurrow** [comment]
Awesome! Looks like the the Peril file moved? Is this it? https://github.com/danger/peril-settings/blob/master/org/aeryn.ts

**Comment by orta** [comment]
Aye

**Comment by orta** [comment]
Probably worth a mention of how it works on moya in peril on the README

**Comment by ashfurrow** [comment]
Yup, added here: https://github.com/RxSwiftCommunity/peril#automatic-pr-checking-with-peril

So I guess the answer to the question fo how Aeryn scales is just "use Peril" – anyone opposed to closing this issue?

**Comment by SD10** [comment]
Wow, so the whole RxSwiftCommunity is now using Peril + Aeryn? Thank you for your work as usual @ashfurrow 🙏 What I needed from this issue is resolved.

**Comment by ashfurrow** [comment]
Yes, that's right! As of only a few days ago: https://github.com/RxSwiftCommunity/contributors/issues/36
