### ISSUE TITLE
Webhook results in 500 error on initial send

### ISSUE THREAD

**Issue by SD10** [Moya/Aeryn#18]
I'm having an issue where the first time the payload is sent it results in a `500 error`. 

If I go to the webhook settings and select `Redeliver` then it goes through with a status code of `200` and no invitation message is sent.

Any idea what the issue could be?

**Comment by ashfurrow** [comment]
Yikes, sorry for the problem. Are you sure the invitation isn't getting sent? This sounds like it's sending the invitation on the first webhook event, then failing while posting the message. The second time, it doesn't post the message, so it works. Can you double-check your message? Maybe it's got some characters that are blowing up Aeryn for some reason. If you're able to post it here, along with any Heroku logs (they contain stack traces) that would help narrow down the exact problem. Thanks!

**Comment by SD10** [comment]
This is the message:

Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

----
I'm going to try removing the emoji. 
Does this need quotes around it when being set as an environment variable?

Sorry I don't have a stack trace, there doesn't seem to be any under the `Heroku -> View Logs`. I'm new to web dev/Heroku so it's possible I don't have them enabled.

Next time the webhook fails I will update this issue with more information.

I'm pretty sure your theory about it sending the invite the first time and it's just not posting the message is correct, because users are receiving invites.

Much appreciated 👍

**Comment by BasThomas** [comment]
^ can confirm that the invite works, even though you 500. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ashfurrow** [comment]
Thanks @BasThomas – that's a big help!

@SD10 I was thinking about the emoji and I think you're right to suspect it. I have a workaround: could you use the GitHub shortcodes? Like instead of the 😃 emoji could you include `:smiley:`?

**Comment by ashfurrow** [comment]
Because if it _is_ the emoji, we could figure out how to fix this line:

https://github.com/Moya/Aeryn/blob/972dbcae2f68d9df127cc71e1eedaa0f8bf72b2a/lib/api.rb#L43

_Or_ we could document this limitation in the readme 😅

**Comment by SD10** [comment]
I tried removing the emoji, used the markdown version of the emoji, wrapped the message in quotes.

Users are getting the invitations, it's just not posting a comment in the PR. 

I wonder if I've set something up wrong. Do I need any other permissions than `admin.org` for the access token?

Here's the response I'm getting if it helps:
![screen shot 2017-11-01 at 4 19 35 am](https://user-images.githubusercontent.com/7445580/32268268-52a7489a-bebc-11e7-8650-02bc17e0dd0f.png)
![screen shot 2017-11-01 at 4 19 55 am](https://user-images.githubusercontent.com/7445580/32268281-5d45ae54-bebc-11e7-8993-4a96ecb9b683.png)

**Comment by ashfurrow** [comment]
Mmmm! Yikes, I think our docs are out of date. Here are the permissions I use for Aeryn: 
![screen shot 2017-11-01 at 10 05 49 am](https://user-images.githubusercontent.com/498212/32278521-5936e622-beec-11e7-8c99-30fce56dec6f.png)

Can you try adding the `public_repo` scope? Sorry about this!

**Comment by SD10** [comment]
That was the issue @ashfurrow 👍 Thank you for helping me resolve this. I submitted an update to the README in #19 to notify others who may face this issue
