### ISSUE TITLE
Configurable threshold

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Aeryn#5]
We currently invite people after a single merged PR, but some orgs might want to make this after 2 PRs, or 3 or whatever. We could check the GitHub API to see how many have been merged before inviting them. It's definitely a nice-to-have, opening this issue to see if there's interest in it.

**Comment by SD10** [comment]
I'd like to have the ability to set some variable like:
`INVITE_THRESHOLD = 3`
I don't know any Ruby but maybe this is something I can look into in the upcoming weeks. I need to know more languages than just Swift 😅

**Comment by ashfurrow** [comment]
Yeah that makes sense 👍 I think we'd have to use the GitHub API to look for all the merged PRs from the same author, and get a count. It shouldn't be _too_ tricky, but let me know if I can help get your development environment setup.

**Comment by SD10** [comment]
I haven't gotten around to this one 😞 I'll probably just start using Aeryn as is.

My plan was to use a threshold of 3 and then scale it down to 1 as the project matures. However, # of PRs could be an arbitrary indicator. Someone could ship a significant feature in a single PR or submit 3 nit PRs improving the docs. 

@ashfurrow What do you think the pros/cons of a configurable threshold are? From your perspective as a maintainer.

**Comment by ashfurrow** [comment]
Hmm, good question. I went with a single merged PR for Aeryn simply because I wanted everyone invited – I just happened to not consider a threshold. It's a totally valid use case! 

You asked about my thoughts as a maintainer, and I can only describe _my_ experience. I've been following the one-merged-PR-gets-you-invited philosophy on the Moya and RxSwiftCommunity organizations for years and I've never had an issue (I do lock the master branch, of course). I have found that the risks are far outweighed by the the benefits of getting more (and more active) contributors. 

I don't think that a threshold necessarily violates that philosophy, but I think it's up to each maintainer to decide what's best for their project. I can't say enough good things about inviting after a single-PR though 😄

**Comment by SD10** [comment]
Thanks, I really appreciate getting your perspective on this 👍 I don't want to change something that I've seen work so well over at Moya myself, so I've adopted the same philosophy

**Comment by ashfurrow** [comment]
So as of #23 we've explicitly identified that no one maintaining Aeryn uses it directly anymore. Aeryn is now just a small feature built atop a more comprehensive infrastructure – hard to believe how far we've come in just a few years, but I guess that's how tech evolves. I'm closing this as a "won't fix", as Aeryn the project is essentially "done".
